spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kkori
    username: postgres
    password: kkori
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080